#ifndef __ASM_ARCH_MAP_ARIES_H
#define __ASM_ARCH_MAP_ARIES_H __FILE__

#define ONEDRAM1G_SHARED_AREA_PHYS  0x35000000
#define ONEDRAM1G_SHARED_AREA_VIRT      0xFC800000
#define ONEDRAM1G_SHARED_AREA_SIZE      (SZ_4M*4)

#endif /* __ASM_ARCH_MAP_ARIES_H */
