#
# Makefile for the kernel Sensor device drivers.
#

# Object files in subdirectories

obj-$(CONFIG_FM_SI4709)		+= fm_si4709/
obj-$(CONFIG_VIBETONZ)		+= vibetonz/
obj-$(CONFIG_LEVEL)			+= level/
obj-$(CONFIG_LTESPI)		+= ltespi/
obj-m		+= wtlfota_dpram/
