#!/system/bin/sh
#
# Script to make boot animations work
# If a custom boot animation exists, we use stock android boot animations,
# otherwise, we will use the stock boot animation.
#
# (c) 2011 - Mark Dietz (imnuts)
# http://twitter.com/imnuts07
#

# Check to see if we have a standard bootanimation.zip file, and if so
# move it to sanim.zip
if ls /system/media/bootanimation.zip || ls /data/local/bootanimation.zip
then
	if ls /data/local/bootanimation.zip
	then
		mv /data/local/bootanimation.zip /system/media/sanim.zip
	else
		mv /system/media/bootanimation.zip /system/media/sanim.zip
	fi
fi

# make /system read-only
mount -o remount,ro /dev/block/stl10 /system

# Lets have an animation
if ls /system/media/sanim.zip
then
	/system/bin/bootanimation
else
	/system/bin/samsungani
fi
