#
# Makefile for the linux rfs-filesystem (kernel 2.4)
#

O_TARGET       := rfs.o

obj-y          += cluster.o code_convert.o dos.o
obj-y          += dir.o file.o inode.o namei.o super.o
obj-y          += log.o log_replay.o
obj-y          += rfs_24.o

obj-m          += $(O_TARGET)

include $(TOPDIR)/Rules.make
