ifeq ($(CONFIG_MACH_CHIEF),y)
obj-$(CONFIG_SAMSUNG_MODEMCTL)		+= modemctl/
obj-$(CONFIG_PHONE_ONEDRAM)		+= onedram/
obj-$(CONFIG_SAMSUNG_PHONE_SVNET)	+= svnet_chief/
else
obj-m +=	modemctl/
obj-m +=	onedram/
obj-m +=	svnet/
endif
